name: EasyStaff
version: '1.2'
main: me.clearedspore.EasyStaff
api-version: '1.16'
authors: [ ClearedSpore ]
depend: [EasyAPI, ProtocolLib]
description: "One of the most advanced staff plugins!"
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - TAB